workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - vendor/bundle
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build unsigned iOS app
        script: |
          cd tap_to_paid
          flutter build ios --debug --no-codesign
    artifacts:
      - tap_to_paid/build/ios/iphonesimulator/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - bt21cse102@iiitn.ac.in # Updated with your email 