workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - vendor/bundle
    scripts:
      - name: Get Flutter packages
        script: |
          cd tap_to_paid
          flutter clean
          flutter pub get
      - name: Install pods
        script: |
          cd tap_to_paid/ios
          pod install
      - name: Build iOS for simulator
        script: |
          cd tap_to_paid
          flutter build ios --debug --no-codesign --simulator
    artifacts:
      - tap_to_paid/build/ios/iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - bt21cse102@iiitn.ac.in 