workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.tap-to-paid"
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.tap-to-paid
    cache:
      cache_paths:
        - ~/.pub-cache
        - vendor/bundle
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Setting up code signing"
          keychain initialize
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod repo update
          pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Xcode build
        script: |
          cd ios
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/ios/archive/*.xcarchive
    publishing:
      email:
        recipients:
          - bt21cse102@iiitn.ac.in
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID 